### ISSUE TITLE
[FEATURE REQUEST]Simple example to show Values from MQTT topics

### ISSUE THREAD

**Issue by Raudi1** [Blueforcer/awtrix3#557]
I'd like to use AWTRIX to display some values from EVCC on my Ulanzi display. There's already a flow, but I can't get it to work. And I don't seem to be the only one: https://github.com/evcc-io/evcc/discussions/10283

EVCC is already publishing the data to the broker under the topics
evcc/site/homePower and evcc/site/pv/1/power etc.

It would be great if there was an easy example how to subscribe to an MQTT topic and display the values.

**Comment by Blueforcer** [comment]
There is no example, because it doesn't work as you think.
You can't just subscribe to another device because Awtrix doesn't know the data structure and how to parse it.
Instead you need to send the data in a predefined and well documented structure.

https://blueforcer.github.io/awtrix3/#/api?id=custom-apps-and-notifications
