### ISSUE TITLE
[FEATURE REQUEST] Better Display Fonts

### ISSUE THREAD

**Issue by Per4merKC** [Blueforcer/awtrix3#566]
# Feature Request
Please update the font so that it is more readable.  (I have seen other font request that are denied, but please consider this feature. I hope the example I provide below illustrates the potential of a readable font.)

### Is your feature request related to a problem?
Yes, poor display of typeface characters

If so, then add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
The font is okay with all uppercase letters, but when using lower case, it is very difficult to read.

### Describe the solution / feature you'd like
I know this is a different code base... but the code at https://github.com/lubeda/EsphoMaTrix/blob/main/UlanziTC001.yaml was able to display fonts more clearly.  (This code base is MUCH easier to use with Home-Assistant so it is my preference. This change would make this solution perfect in my opinion.)  I'm not asking for custom fonts, although that would be a nice option.  A good readable font is all that is necessary.

### Additional context
The video at the following link shows how clearly the lower case "w" displays.  

https://packaged-media.redd.it/kqt594iaylwa1/pb/m2-res_1080p.mp4?m=DASHPlaylist.mpd&v=1&e=1718690400&s=b48b621be01692bf20dd8c3406aaa7445f975b76#t=0

**Comment by Blueforcer** [comment]
Mhh, how about asking for changing the letter "w" then?
1. That it is easier may be your opinion, but not that of thousands of other users. AWTRIX is compatible with all other smart home systems and beyond, as it speaks a simple API language. Mapping all the functionalities that AWTRIX can do is not even possible via the HA discovery function.
2. The font is a copy of LaMetric, and they have already thought about the readability. (Wich is btw uppercase only)
3. (And the main reason) Because AWTRIX offers way more functions, a different font size is not possible at all, because then, for example, there is no more space to display a progress bar or the days of the week, and the time would no longer fit into the timeapp with the calendar. etc. etc

So we can discuss adjusting a letter here and there, but the font will remain the same.
